#!/bin/bash
# M161 -- Select Probe Input
# P0 No Probe
# P1 X-Axis Prox
# P2 Y-Axis Prox
# P3 Z-Axis Prox
# 
# Machine must be homed before using!!!!
# 
halcmd unlinkp hm2_7i76e.0.7i76.0.0.input-16-not
halcmd unlinkp hm2_7i76e.0.7i76.0.0.input-17-not
halcmd unlinkp hm2_7i76e.0.7i76.0.0.input-18-not

if [[ $1 == "1.000000" ]]
	then 
	echo Selecting X Prox as Probe Input
	halcmd net probe-in hm2_7i76e.0.7i76.0.0.input-16-not
fi

if [[ $1 == "2.000000" ]]
	then 
	echo Selecting Y Prox as Probe Input
	halcmd net probe-in hm2_7i76e.0.7i76.0.0.input-17-not
fi

if [[ $1 == "3.000000" ]]
	then 
	echo Selecting Z Prox as Probe Input
	halcmd net probe-in hm2_7i76e.0.7i76.0.0.input-18-not
fi
